### ISSUE TITLE
import tensorflow as tf fails

### ISSUE THREAD

**Issue by mpkuse** [jetsonhacks/installTensorFlowTX2#21]
Hi, 
I installed tensorflow on my tx2 using your wheels. 

My config 
```
[nvidia@tegra-ubuntu jetsonUtilities]$ python jetsoninfo.py 
 Hardware Model Name not available
 L4T 27.1.0
 Board: t186ref
 Ubuntu 16.04 LTS
 Kernel Version: 4.4.15-tegra
```

As I try to import tensorflow
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

```

Help appreciated!

**Comment by jetsonhacks** [comment]
The wheel files are for L4T 28.1.
I believe that the major difference is that 27.1 uses cuDNN 5, 28.1 uses cuDNN 6.
You must have both CUDA and cuDNN installed.
