### ISSUE TITLE
tx2 and python 2.7 

### ISSUE THREAD

**Issue by aysegulucar2016** [jetsonhacks/installTensorFlowTX2#25]
Hi,
After instalting Jetpack 3.2 (hereby cuda 9.0) on TX2, I installed tensorflow with  sudo pip2 install tensorflow-1.6.0rc1-cp27-cp27mu-linux_aarch64.whl.

I stucked in the error after installing.  How can I get rid of the error  libcusolver.so.8.0 of cuda 8?
Thanks

nvidia@tegra-ubuntu:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

**Comment by jetsonhacks** [comment]
The .whl files are compiled against CUDA 8.0. If you want to use CUDA 9.0, please see:

https://github.com/JasonAtNvidia/JetsonTFBuild
